apiVersion: v1
kind: Service
metadata:
  name: mysqlserver
  namespace: wordpresssite
  labels:
    app: mysqlserver
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: mysqlserver
    tier: mysql
  clusterIP: None
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: mysqlserver
  namespace: wordpresssite
  labels:
    app: mysqlserver
spec:
  selector:
    matchLabels:
      app: mysqlserver
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysqlserver
        tier: mysql
    spec:
      containers:
      - image: mysql:5.6
        name: mysqlserver
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: backend-credentials
              key: backend-password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: azurefile