apiVersion: v1
kind: Service
metadata: 
  name: wordpresssite
  namespace: wordpresssite
spec: 
  selector: 
    app: wordpresssite
  ports:
    - name: wordpresssite
      port: 80
      targetPort: 80
  type: ClusterIP
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: wordpresssite
  labels:
    app: wordpresssite
  namespace: wordpresssite
spec:
  selector:
    matchLabels:
      app: wordpresssite
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpresssite
        tier: frontend
    spec:
      containers:
      - image: wordpress:4.8-apache
        name: wordpresssite
        env:
        - name: WORDPRESS_DB_HOST
          value: mysqlserver
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: backend-credentials
              key: backend-password
        ports:
        - containerPort: 80
          name: wordpresssite
        volumeMounts:
        - name: wordpress-persistent-storage
          mountPath: /var/www/html
      volumes:
      - name: wordpress-persistent-storage
        persistentVolumeClaim:
          claimName: azurefile
